# Generated by Django 3.1.8 on 2021-04-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('squadron', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'crime_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_lock_out', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_name', models.CharField(max_length=255)),
                ('alternate_email', models.CharField(max_length=180, null=True)),
                ('roles', models.TextField(default='[]')),
                ('squadron_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('seen_welcome_message', models.BooleanField(default=False)),
                ('has_gravatar', models.BooleanField(default=False)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.customrank')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.rank')),
                ('squadron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('status', models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='commander.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ThargoidActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField()),
                ('date_killed', models.DateTimeField()),
                ('minor_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.minorfaction')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('thargoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thargoidvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thargoid_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FactionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateField()),
                ('reward', models.IntegerField()),
                ('earning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.earningtype')),
                ('minor_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_faction', to='squadron.minorfaction')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('target_minor_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_minor_faction', to='squadron.minorfaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faction_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim', models.CharField(blank=True, max_length=255, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('bounty', models.IntegerField(blank=True, null=True)),
                ('committed_on', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commander.crimetype')),
                ('minor_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.minorfaction')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crime',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=20, null=True)),
                ('asset', models.BigIntegerField(blank=True, null=True)),
                ('credits', models.BigIntegerField(blank=True, null=True)),
                ('loan', models.IntegerField(blank=True, null=True)),
                ('combat_progress', models.IntegerField(default=0)),
                ('trade_progress', models.IntegerField(default=0)),
                ('explore_progress', models.IntegerField(default=0)),
                ('mercenary_progress', models.IntegerField(default=0)),
                ('exobiologist_progress', models.IntegerField(default=0)),
                ('federation_progress', models.IntegerField(default=0)),
                ('empire_progress', models.IntegerField(default=0)),
                ('cqc_progress', models.IntegerField(default=0)),
                ('combat', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='combat', to='squadron.rank')),
                ('cqc', models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, related_name='cqc', to='squadron.rank')),
                ('empire', models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='empire', to='squadron.rank')),
                ('exobiologist', models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, related_name='exobiologist', to='squadron.rank')),
                ('explore', models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='explore', to='squadron.rank')),
                ('federation', models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='federation', to='squadron.rank')),
                ('mercenary', models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, related_name='mercenary', to='squadron.rank')),
                ('trade', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='squadron.rank')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commander',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('bounties_claimed', models.IntegerField()),
                ('systems_scanned', models.IntegerField()),
                ('bodies_found', models.IntegerField()),
                ('saa_scan_completed', models.IntegerField()),
                ('efficiency_achieved', models.IntegerField()),
                ('market_buy', models.IntegerField()),
                ('market_sell', models.IntegerField()),
                ('missions_completed', models.IntegerField()),
                ('mining_refined', models.IntegerField()),
                ('stolen_goods', models.IntegerField()),
                ('cg_participated', models.IntegerField()),
                ('crimes_committed', models.IntegerField()),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_counter',
                'managed': True,
            },
        ),
    ]
