# Generated by Django 3.1.8 on 2021-05-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commander', '0002_commanderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('game_datetime', models.DateTimeField(blank=True, null=True)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('progress_code', models.CharField(blank=True, max_length=1, null=True)),
                ('progress_percent', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_log',
                'managed': True,
            },
        ),
    ]
