# Generated by Django 3.1.8 on 2021-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0003_journallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journallog',
            name='file',
            field=models.FileField(upload_to='journal_log/'),
        ),
    ]
