# Generated by Django 3.1.8 on 2021-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0004_auto_20210501_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journallog',
            old_name='game_datetime',
            new_name='game_end',
        ),
        migrations.AddField(
            model_name='journallog',
            name='game_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
