# Generated by Django 3.1.8 on 2021-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0005_auto_20210501_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallog',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='journallog',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
