# Generated by Django 3.2.2 on 2021-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0005_alter_earninghistory_squadron'),
    ]

    operations = [
        migrations.AddField(
            model_name='journallog',
            name='parser_time',
            field=models.FloatField(null=True),
        ),
    ]
