# Generated by Django 3.1.8 on 2021-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0006_auto_20210501_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journallog',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='journallog',
            name='game_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='journallog',
            name='game_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
