# Generated by Django 3.2.2 on 2021-05-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0007_journallog_rows_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycounter',
            name='black_market',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitycounter',
            name='illegal_goods',
            field=models.IntegerField(default=0),
        ),
    ]
