# Generated by Django 3.1.8 on 2021-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0007_auto_20210501_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journallog',
            name='progress_code',
            field=models.CharField(default='Q', max_length=1),
        ),
    ]
