# Generated by Django 3.2.2 on 2021-05-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0008_auto_20210511_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_fleetcarrier',
            field=models.BooleanField(default=False),
        ),
    ]
