# Generated by Django 3.2.2 on 2021-05-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0003_auto_20210508_0311'),
        ('commander', '0009_userprofile_has_fleetcarrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='squadron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron'),
        ),
    ]
