# Generated by Django 3.2.2 on 2021-06-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0010_alter_crime_squadron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earninghistory',
            name='earned_on',
            field=models.DateField(db_index=True),
        ),
    ]
