# Generated by Django 3.2.1 on 2021-05-06 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MinorFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player_faction', models.BooleanField(default=False)),
                ('eddb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'minor_faction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('color_power', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'power',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('perm_mask', models.IntegerField()),
            ],
            options={
                'db_table': 'rank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Squadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_code', models.CharField(blank=True, max_length=4, null=True)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
                ('home_base', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('require_approval', models.CharField(max_length=1)),
                ('invite_link', models.IntegerField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.faction')),
                ('power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.power')),
            ],
            options={
                'db_table': 'squadron',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('badge_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SquadronTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.tags')),
            ],
            options={
                'db_table': 'squadron_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.SmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
            ],
            options={
                'db_table': 'custom_rank',
                'managed': True,
            },
        ),
    ]
