# Generated by Django 3.2.2 on 2021-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorfaction',
            name='player_faction',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
