# Generated by Django 3.2.2 on 2021-05-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0002_alter_minorfaction_player_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorfaction',
            name='eddb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='minorfaction',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='minorfaction',
            name='player_faction',
            field=models.BooleanField(default=False),
        ),
    ]
