# Generated by Django 3.2.2 on 2021-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0004_squadron_primary_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='group_code',
        ),
        migrations.AddField(
            model_name='tags',
            name='collection',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='fdev_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['fdev_id'], name='tags_fdev_id_fc9fc7_idx'),
        ),
    ]
