# Generated by Django 3.2.2 on 2021-06-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0005_auto_20210604_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadron',
            old_name='id_code',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='squadron',
            name='superpower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.faction'),
        ),
        migrations.AlterField(
            model_name='squadron',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.minorfaction'),
        ),
        migrations.CreateModel(
            name='SquadronRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(db_index=True)),
                ('cmdr_name', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField()),
                ('request_date', models.DateTimeField()),
                ('last_online', models.DateTimeField()),
                ('rank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squadron_rank', to='squadron.rank')),
                ('rank_combat', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='rank_combat', to='squadron.rank')),
                ('rank_exobiologist', models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, related_name='rank_exobiologist', to='squadron.rank')),
                ('rank_explore', models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='rank_explore', to='squadron.rank')),
                ('rank_mercenary', models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, related_name='rank_mercenary', to='squadron.rank')),
                ('rank_trade', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='rank_trade', to='squadron.rank')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
            ],
            options={
                'db_table': 'squadron_roster',
                'managed': True,
            },
        ),
    ]
