# Generated by Django 3.2.2 on 2021-06-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0007_squadronroster_has_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='fdev_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squadron',
            name='invite_link',
            field=models.BooleanField(default=False),
        ),
    ]
