# Generated by Django 3.2.2 on 2021-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0008_auto_20210607_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadron',
            name='require_approval',
            field=models.BooleanField(default=True),
        ),
    ]
