# Generated by Django 3.2.2 on 2021-06-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0009_alter_squadron_require_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='owner_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squadron',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
