# Generated by Django 3.2.2 on 2021-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0011_squadron_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='accept_new_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squadron',
            name='squadron_tags',
            field=models.ManyToManyField(blank=True, to='squadron.Tags'),
        ),
    ]
