# Generated by Django 3.2.2 on 2021-06-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0012_auto_20210607_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SquadronTags',
        ),
    ]
