# Generated by Django 3.2.2 on 2021-06-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0013_delete_squadrontags'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='owner_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
