# Generated by Django 3.2.2 on 2021-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0014_squadron_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadronroster',
            name='leave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
