# Generated by Django 3.2.2 on 2021-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0015_squadronroster_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadronroster',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
