# Generated by Django 3.2.2 on 2021-06-10 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0016_squadronroster_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
