# Generated by Django 3.2.2 on 2021-06-10 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0017_squadron_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='established_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
