# Generated by Django 3.2.2 on 2021-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0018_squadron_established_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(db_index=True, max_length=12)),
                ('content', models.TextField()),
                ('last_updated', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'leaderboard',
                'managed': True,
            },
        ),
    ]
