# Generated by Django 3.2.2 on 2021-06-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0020_leaderboard_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='squadron',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron'),
            preserve_default=False,
        ),
    ]
