# Generated by Django 3.2.2 on 2021-06-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron', '0021_leaderboard_squadron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='content',
            field=models.JSONField(),
        ),
    ]
