# Generated by Django 3.1.8 on 2021-04-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squadron', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_string', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('list_order', models.SmallIntegerField()),
                ('admin_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'acl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_flag', models.IntegerField()),
                ('pinned_flag', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommunityGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
                ('market_name', models.CharField(max_length=50)),
                ('starsystem_name', models.CharField(max_length=50)),
                ('activityType', models.CharField(max_length=50)),
                ('target_qty', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('objective', models.TextField()),
                ('news', models.TextField()),
                ('bulletin', models.TextField()),
            ],
            options={
                'db_table': 'community_goal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('posted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'debug',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EarningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mission_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'earning_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('error_id', models.CharField(blank=True, max_length=50, null=True)),
                ('error_msg', models.TextField()),
                ('debug_info', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('data_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'error_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GalnetNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('nid', models.IntegerField()),
                ('ed_date', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Galnet news',
                'db_table': 'galnet_news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('locale_name', models.CharField(max_length=50)),
                ('has_translation', models.IntegerField()),
                ('percent_complete', models.SmallIntegerField()),
                ('verified', models.IntegerField()),
            ],
            options={
                'db_table': 'language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('show_flag', models.IntegerField()),
                ('show_login', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'motd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ThargoidVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reward', models.IntegerField()),
            ],
            options={
                'db_table': 'thargoid_variant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.announcement')),
                ('motd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.motd')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'read_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_filename', models.CharField(max_length=255)),
                ('game_datetime', models.DateTimeField()),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('progress_code', models.CharField(blank=True, max_length=1, null=True)),
                ('progress_percent', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Edmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(blank=True, null=True)),
                ('entered_at', models.DateTimeField()),
                ('processed_flag', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edmc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=255)),
                ('slide_label', models.CharField(max_length=128)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('squadron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadron.squadron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carousel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CapiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=20)),
                ('data', models.TextField()),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capi_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip', models.CharField(max_length=16)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=64)),
                ('region_name', models.CharField(max_length=128)),
                ('city_name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zip_code', models.CharField(max_length=30)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('google_2fa_trust_flag', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_history',
                'managed': True,
            },
        ),
    ]
