# Generated by Django 3.1.8 on 2021-05-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportQueue',
        ),
    ]
