# Generated by Django 3.2.2 on 2021-05-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sessiontracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontracker',
            name='hash_key',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
