# Generated by Django 3.2.2 on 2021-06-03 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_parserlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="galnetnews",
            old_name="ed_date",
            new_name="galnet_date",
        ),
        migrations.AddField(
            model_name="galnetnews",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="galnetnews",
            name="langcode",
            field=models.CharField(default="en", max_length=2),
            preserve_default=False,
        ),
    ]
