# Generated by Django 3.2.2 on 2021-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210603_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galnetnews',
            old_name='langcode',
            new_name='lang_code',
        ),
    ]
