# Generated by Django 3.2.2 on 2021-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_galnetnews_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galnetnews",
            name="lang_code",
            field=models.CharField(max_length=5),
        ),
    ]
