# Generated by Django 3.2.2 on 2021-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_galnetnews_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningtype',
            name='category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
